# Dockerfile-php
FROM php:8.2-apache

# Instalace GD extension pro práci s obrázky
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libwebp-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
    && docker-php-ext-install gd \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY public/php/ /var/www/html/php/
COPY public/data/ /var/www/html/data/
RUN chown -R www-data:www-data /var/www/html/data
EXPOSE 80
